### ISSUE TITLE
Small bug: current user needs to be added to the docker group

### ISSUE THREAD

**Issue by rjalexa** [slowrunner/wali_pi5#1]
Your scripts work great but "2_install_docker_pkgs.sh" could fail if the current user is not in the docker group already.

You should just add a :
`sudo usermod -aG docker $USER`
before you try to run the hello world image.

Thanks for your scripts, very useful to install docker on a Raspberry Pi

**Comment by slowrunner** [comment]
Thanks for the input.  I'll take a look.

**Comment by slowrunner** [comment]
Added  https://github.com/slowrunner/wali_pi5/commit/9492b0563c1d43995bd2447e922278c5df466a27
Thanks.
